# Add this to your existing values.yaml
replicaCount: 1

mqttBroker:
  image: eclipse-mosquitto:latest
  name: mqtt-broker
  ports:
    - name: mqtt
      containerPort: 1883
  resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
