apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitops-mqtt-aks.fullname" . }}
  labels:
    {{- include "gitops-mqtt-aks.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "gitops-mqtt-aks.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gitops-mqtt-aks.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.mqttBroker.name }}
          image: "{{ .Values.mqttBroker.image }}"
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
