apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitops-mqtt-aks.fullname" . }}-mqtt-broker
  labels:
    {{- include "gitops-mqtt-aks.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: mqtt
  selector:
    {{- include "gitops-mqtt-aks.selectorLabels" . | nindent 6 }}
